# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "CJthJQvTnz/5mV7YwL6gB+M9zBvMO6Md9wGlApI37zMdV/d6b4DuW71ov4hnhh9RUbG3xNnVZGVCEQBFHArYDJ4P5/n9LrcLBNx29p8ckxDDG0A7PBhEDfYo8LPUaYmog//nTHl3tL+fsRY0A1l/sxx3DfaJVeIWjrpSd/RbG/uSVfsP/RIidEAbNSLe8hBN6pkJsIv1xL6yRCz12e8X4zaHxKNGOa2q9xflfdnXJITsWNAgXS7l2uwjBfxZGRoGlz6P3VR6Uu7qyigmbeZtL4VsfhbIKl4OgGXLHroZfngUEjt06KlJU6QAKq+AchZhaRpO+SsHGlTmzekTONlj0i/Fxvu6jv/sYTqRz3+wn1p+kekJGe1F4nfd+9I//+Lwrsa7XJeRdfcavTipHMnVtiYm4BXaooExZWJZ9+XMLT/WrPaRAMuGt5JVyJOQ6CPh9TLBvDaoEmdxGb6q6asbYe1OL/iEDbhkd2snh7xndh1l8NqKkOiMf5MwYZJksDL6O1Pn5iI/bh7hanebxnocHW2f9MhxsRTVsSEYs3PsnAOOU69bV0+AOMSgRE3KBLrgaZ/z3V9k8IHW5IpmuTyHDcJbgTT1C2PN4kWviCryTC/volcA7clu2ZqilBcpTqy6mWHl0E7heKgcydNWBghrqNaESWP4cDVU8qLur7pB4xs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
