appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YTsRkQiZb9hIVy6ZTeSWvWoaOLgcaPVOOFj61C4ynXkJ/gN7QiH/oKLpEMtMGpU34U7NcFqVbMChbCQvMCIQmhzEH1ak3EXS4oPreDKClFWEfYwF7bRvRV/uBkfn4zD7kRL8NAMLXqmNrFzytQTCNexb9+rmlYdy8P9dBHu0nTHumFN4npfxihIg01MrD+latfhcwDwdARx9AVr9qCRjCY4dKMelyM6o1Ja2e9qY6Hxf0xq9pxpR6LIyXk7MdBLli4Btc9EV0FjQevc7nFazX7mjzOyKtFnUD/BSy0KoZZ6Nx9Sk8OrhuQeUkOy6KUM/0Oat3GhWIhoIuIZSSd3eTCk1hH+dtByYcuklLcsS5T9uQQb3x0NXIWhJKGnqiRAU7vK3BvnZJtmRfkX/X136aiTqjwLTPVp7WOzfunsbq0V0jkgc/zj1NJ0lGoyap2SK1ZlTDpw5ffdcnThhfTtBQiMO65Ry2uyyNO8+SsBKIZZj+6Gr7Eqd5zefvzwfxfF/E+CwFkK5Z8hIL3JIm7SAJZCfQZXPLhZEgTArrcqz5pd//ZF9DRT5Rlqt1Rgz0fm2aqJXFVP0jRrbKH5f3ecgpMRU52bJ4QsZdBGjesrp5PSfMzZcqGZjsFEtbjZk033OO6ptGVRB7+kxu1mafr+WUMSEXEgSRohbaAi85pJwhs0=}
provider:
  win: azure
conda_forge_output_validation: false
